### PR TITLE
Added banner: prepend a defined string to the resulting file.

### PR DESCRIPTION
**Pull request by dennisguse**

### CODE REVIEW

**Comment by miensol** [comment]
Hi Dennis,

I appreciate your interest in project :+1: However I do think prepending content to a file could be done easily by using the output of this plugin with e.g. [concat](https://github.com/gruntjs/grunt-contrib-concat). Have you considered such setup?

**Comment by dennisguse** [comment]
Hey Piotr,

jupp, I looked into that.
Concat would work, but it is not my favorite solution.
For concat, I would need to create a temporary file and then prepend the banner.
Somehow doesn't feel good...

And adding the banner option would be in line at least concat and uglify ;)

PS: 
While checking the uglify code, I found that they process `options.banner` using `var banner = grunt.template.process(options.banner);`.
I did not include this in the pull request, as the banner that I use contains Grunt variables and it works even without `template.process`.
My test banner: 
```
        concat_in_order_jsdoc: {
            your_target: {
                options: {
                    banner: '/*!\n<%= pkg.name %>\n<%= pkg.homepage %>\n<%= pkg.repository %>: <%= meta.revision %>\n<%= pkg.license %>\n<%= grunt.template.today() %>\n*/\n'
                },
                files: {
                    'thefragebogen.js': ['build/*.js']
                }
            }
        }
```

PPS: concat_in_order is really awesome ;)

**Comment by dennisguse** [comment]
Any chance to merge this change?

**Comment by miensol** [comment]
Yup, thanks 👍  Sorry for the delay. Will try to publish new version soon.

**Comment by dennisguse** [comment]
Öhm - any chance to release the new version?
I would like to upgrade grunt-concat-in-order to use this *awesome* feature ;)

**Comment by miensol** [comment]
@dennisguse  A new version has been released. Sorry for the long delay.

**Comment by dennisguse** [comment]
@miensol I think it should be the other way around: thanks for your time!

**Pull request merged**
